create table brands
(
    Id          int identity
        constraint PK_brands
            primary key,
    Name        nvarchar(255)                                   collate Latin1_General_CI_AS not null,
    Description nvarchar(2000),
    is_active   bit       default CONVERT([bit], 0)             not null,
    created_at  datetime2 default '0001-01-01T00:00:00.0000000' not null,
    deleted_at  datetime2,
    modified_at datetime2,
    logo        nvarchar(255)
)
go

create index IX_brands_Name
    on brands (Name)
go

INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Similac', N'Similac là một trong những thương hiệu sữa của Abbott - Tập đoàn chăm sóc sức khỏe hàng đầu thế giới đến từ Hoa Kỳ. Thành lập năm 1888, Abbott chuyên nghiên cứu, phát triển, sản xuất và đưa ra các sản phẩm và dịch vụ chăm sóc sức khỏe. Những sản phẩm của Abbott trải rộng từ dược phẩm, thực phẩm dinh dưỡng đến công nghệ y sinh và thiết bị chuyên dụng phục vụ trong y tế.', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:31:02.1473728', N'https://i.imgur.com/OP5vOM3.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Enfa', N'Enfa là thương hiệu dinh dưỡng nổi tiếng bậc nhất Hoa Kỳ được nhiều ba mẹ ủng hộ và được khuyên dùng bởi các chuyên gia chăm sóc sức khoẻ hàng đầu thế giới. Thương hiệu luôn tiên phong trong công cuộc phát triển những sản phẩm dinh dưỡng chất lượng và an toàn dành cho nhiều đối tượng, bao gồm: trẻ sơ sinh, trẻ nhỏ, mẹ bầu và mẹ đang cho con bú. Enfa gồm các dòng sản phẩm chính như:  Enfamama dành cho mẹ bầu và mẹ cho con bú: bổ sung dinh dưỡng giúp thai kỳ trọn vẹn, đảm bảo sức khoẻ cho cả mẹ và thai nhi.  Các dòng dinh dưỡng bổ sung cho sơ sinh và trẻ nhỏ theo giai đoạn như: Enfa A+1, Enfa A+2, Enfa Grow,...  Các dòng dinh dưỡng đặc biệt cho trẻ như: Enfalac,…', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:32:41.1856368', N'https://i.imgur.com/daIfYcI.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Aptamil', N'Aptamil là sản phẩm dinh dưỡng thuộc tập đoàn Danone (Pháp) - tập đoàn dinh dưỡng trẻ em Số 1 Châu Âu. Thương hiệu được thành lập tại Đức vào năm 1968 và được bán tại Anh năm 1983. Trải qua hơn 40 năm kinh nghiệm trong lĩnh vực, cùng đội ngũ hơn 250 bác sĩ y khoa, chuyên gia dinh dưỡng, nhà khoa học không ngừng nỗ lực trong công cuộc nghiên cứu sữa mẹ và dinh dưỡng đầu đời, Aptamil đã thành công phát triển những công thức độc đáo, đáp ứng nhu cầu dinh dưỡng cho bé yêu ở từng thời kì phát triển.      Những nỗ lực của Aptamil đã đưa thương hiệu trở thành cái tên hàng đầu thế giới trong lĩnh vực dinh dưỡng dành cho trẻ nhỏ. Bên cạnh đó, Aptamil vẫn luôn là nguồn thông tin đáng tin cậy cho bố mẹ và nhiều chuyên gia trong ngành. ', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:33:08.3779574', N'https://i.imgur.com/ItdfgJg.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Nestlé NAN', N'Nhãn hàng sữa bột NAN đến từ Thụy Sĩ mang đến những lựa chọn dinh dưỡng hợp lý theo từng độ tuổi, từng giai đoạn phát triển, giúp trẻ phát triển trọn tiềm năng. Thương hiệu NAN cam kết đồng hành cùng ba mẹ trên hành trình dành trọn những điều tốt nhất cho con. Cam kết đó là kim chỉ nam và cũng chính là DNA của thương hiệu NAN. Với hơn 155 năm kinh nghiệm Nestlé không ngừng tiên phong nghiên cứu & sáng tạo trong lĩnh vực dinh dưỡng dành cho trẻ nhỏ và ứng dụng vào các sản phẩm NAN, để đồng hành cùng ba mẹ nuôi dưỡng trọn tiềm năng trong con.', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:45:25.5097767', N'https://i.imgur.com/sd2WlKh.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Meiji', N'Meiji từ lâu được biết đến là một trong những thương hiệu sản xuất sữa bột cho bé lâu đời bậc nhất tại Nhật Bản và châu Á. Được thành lập năm 1917, sau hơn 100 năm hình thành và phát triển, Meiji đã khẳng định được giá trị thương hiệu số 1 với dây chuyền sản xuất hiện đại, cho ra những sản phẩm chất lượng cao nhất. Tất cả sản phẩm Meiji dù ở các thị trường nước ngoài hay thị trường trong nước đều được sản xuất tại cùng một nhà máy ở tỉnh Saitama, Nhật Bản.     Hướng tới việc tạo ra được loại sữa bột có thành phần gần gũi với trẻ nhỏ, Meiji đã thực hiện dự án “Khoa học sữa mẹ” và cho ra những dòng sữa phù hợp nhất. Tất cả các dòng sữa bột Meiji đều mang lại cho bé thể trạng và sự phát triển toàn diện nhất dựa trên sức mạnh tự nhiên có từ sữa.  ', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:35:24.7012999', N'https://i.imgur.com/5ZMAOmb.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Friso', N'Đôi nét về thương hiệu  Friso Gold là thương hiệu sữa thuộc FrieslandCampina, một trong những tập đoàn sữa liên hợp lớn nhất trên thế giới với doanh thu hàng năm lên đến 10,3 tỷ euro. Tập đoàn sở hữu hơn 14.132 trang trại sữa thành viên ở Hà Lan, Đức và Bỉ, và hơn 140 năm kinh nghiệm trong kinh doanh liên hợp nông trại sữa. Tập đoàn đóng trò quan trọng trong việc cung cấp thực phẩm cho hàng trăm triệu người trên toàn thế giới.  Đồng hành với các nông dân giàu kinh nghiệm trong ngành sữa, các chuyên gia đến thừ thương hiệu Friso không ngừng nghiên cứu và cải tiến, nhằm cung cấp cho mẹ và bé nguồn sữa đạt chất lượng tốt nhất. Friso Gold – với nguồn sữa mát 100% từ Hà Lan, giúp con tự tin lớn khôn trên mọi bước đi trong hành trình khôn lớn.  Một số ưu điểm nổi bật của thương hiệu   . Nguồn sữa mát 100% từ Hà Lan  Với 150 năm kinh nghiệm trong ngành sữa, các chú bò Friso được cung cấp chế độ ăn riêng biệt để đảm bảo tạo ra nguồn sữa chất lượng với các phân tử đạm sữa mềm nhỏ tự nhiên, giúp bé hấp thu nhanh và tiêu hóa dễ dàng', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:35:04.7955536', N'https://i.imgur.com/tkmk85a.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Pediasure', N'Pediasure là một trong những thương hiệu sữa của Abbott - Tập đoàn chăm sóc sức khỏe hàng đầu thế giới đến từ Hoa Kỳ. Thành lập năm 1888, Abbott chuyên nghiên cứu, phát triển, sản xuất và đưa ra các sản phẩm và dịch vụ chăm sóc sức khỏe. Những sản phẩm của Abbott trải rộng từ dược phẩm, thực phẩm dinh dưỡng đến công nghệ y sinh và thiết bị chuyên dụng phục vụ trong y tế.', 1, N'2024-05-22 00:00:00.6000000', null, N'2024-07-20 15:34:44.9186953', N'https://i.imgur.com/Hp73Rbe.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'NutiFood', null, 1, N'2024-05-22 00:00:00.6000000', null, null, N'https://i.imgur.com/5sY47RP.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Abbott Grow', null, 1, N'2024-06-17 00:00:00.0000000', null, null, N'https://i.imgur.com/0eUvc05.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'YokoGold', N'YOKOGOLD  là 1 trong những thương hiệu sữa thuộc Vinamilk - Tập đoàn dinh dưỡng hàng đầu Việt Nam, thương hiệu Quốc gia và thuộc Top 50 Công ty sữa lớn nhất thế giới. Trải qua gần 40 năm miệt mài nghiên cứu và tích cực đổi mới, cái tên Vinamilk đã nhận được sự tin yêu của người dân Việt Nam và cả người nước ngoài. Tuy nhiên, không vì thành tích đó mà Vinamilk dừng bước, thương hiệu vẫn không ngừng nỗ lực khẳng định mình qua tinh thần cầu tiến, sáng tạo trong cả công nghệ sản xuất và tính đa dạng qua từng dòng sản phẩm. Các sản phẩm của Vinamilk luôn đạt chất lượng hàng đầu theo tiêu chuẩn quốc tế và đáp ứng được nhu cầu của nhiều đối tượng khách hàng.', 1, N'2024-06-17 00:00:00.0000000', null, N'2024-07-20 15:31:36.0062653', N'https://i.imgur.com/Z1ezeD8.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'PureLac', null, 0, N'2024-06-17 00:00:00.0000000', null, null, N'https://i.imgur.com/mKRLb5I.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Humana', N'Humana là một trong 2 tập đoàn đứng hàng đầu tại Đức, nằm trong TOP 10 các Công ty lớn nhất của châu Âu. Thành lập vào 1950, với hơn 70 năm kinh nghiệm trong công cuộc nghiên cứu, sản xuất sữa và các sản phẩm chế biến từ sữa cho bé yêu, Humana đã thành công xuất khẩu các dòng sản phẩm đa dạng, chất lượng cao đến với gần 70 quốc gia trên toàn thế giới.  100% sản phẩm của Humana được sản xuất dưới quy trình khép kín, được kiểm soát hoàn toàn theo quy trình nghiêm ngặt: sữa bò chất lượng cao thu được từ các nông trại xanh & sạch, được bảo quản lạnh và vận chuyển nhanh tới các nhà máy. Tại đây, Humana tiếp tục áp dụng quy trình công nghệ hiện đại trong khâu sản xuất, chế biến và đóng gói, đảm bảo cho ra thị trường những dòng sản phẩm đạt chất lượng cao để cung ứng cho người tiêu dùng toàn cầu .', 1, N'2024-06-17 00:00:00.0000000', null, N'2024-07-20 15:36:00.1106217', N'https://i.imgur.com/bnucNnu.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu Morinaga', null, 1, N'2024-06-19 11:10:24.0000000', null, null, N'https://i.imgur.com/jGV581F.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu Matilia', null, 1, N'2024-06-19 11:10:45.0000000', null, null, null);
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu Enfamama', null, 1, N'2024-06-19 11:11:02.0000000', null, null, null);
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu Similac Mom', null, 1, N'2024-06-19 11:11:40.0000000', null, null, N'https://i.imgur.com/Vbs3UBa.jpeg');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu XO', null, 1, N'2024-06-19 11:11:53.0000000', null, null, null);
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu FrisoMum', null, 1, N'2024-06-19 11:12:21.0000000', null, null, null);
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Sữa bầu Meji Mama', null, 1, N'2024-06-19 11:13:48.0000000', null, null, null);
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Vinamilk', null, 1, N'2024-06-25 16:23:06.0000000', null, null, N'https://i.imgur.com/2iJ3ut4.png');
INSERT INTO yumilk.dbo.brands (name, description, is_active, created_at, deleted_at, modified_at, logo) VALUES (N'Milk1213123213', N'asdasd', 0, N'2024-07-19 04:36:42.2042190', N'2024-07-22 19:50:34.9280540', N'2024-07-22 12:50:35.0050530', N'https://i.imgur.com/FNNjlxS.jpeg');
